version: '3.1'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm-alpine
    volumes:
      - ./backend:/backend
    ports:
      -  9000:9000
  pgsql:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: developer
        POSTGRES_PASSWORD: uVK4PBfdNBncWLbmZMKG
        POSTGRES_DB: chat

  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"